/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vavi_speech_aquestalk2_AquesTalk2 */

#ifndef _Included_vavi_speech_aquestalk2_AquesTalk2
#define _Included_vavi_speech_aquestalk2_AquesTalk2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vavi_speech_aquestalk2_AquesTalk2
 * Method:    synthe
 * Signature: (Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_vavi_speech_aquestalk2_AquesTalk2_synthe
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
