/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vavi_speech_aquestalk_AquesTalkDa */

#ifndef _Included_vavi_speech_aquestalk_AquesTalkDa
#define _Included_vavi_speech_aquestalk_AquesTalkDa
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vavi_speech_aquestalk_AquesTalkDa
 * Method:    playSync
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_vavi_speech_aquestalk_AquesTalkDa_playSync
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     vavi_speech_aquestalk_AquesTalkDa
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_vavi_speech_aquestalk_AquesTalkDa_create
  (JNIEnv *, jobject);

/*
 * Class:     vavi_speech_aquestalk_AquesTalkDa
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vavi_speech_aquestalk_AquesTalkDa_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vavi_speech_aquestalk_AquesTalkDa
 * Method:    play
 * Signature: (JLjava/lang/String;IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_vavi_speech_aquestalk_AquesTalkDa_play
  (JNIEnv *, jobject, jlong, jstring, jint, jint, jstring, jint);

/*
 * Class:     vavi_speech_aquestalk_AquesTalkDa
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vavi_speech_aquestalk_AquesTalkDa_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vavi_speech_aquestalk_AquesTalkDa
 * Method:    isPlay
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_vavi_speech_aquestalk_AquesTalkDa_isPlay
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
