/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vavi_speech_aquestalk2_AquesTalk2Da */

#ifndef _Included_vavi_speech_aquestalk2_AquesTalk2Da
#define _Included_vavi_speech_aquestalk2_AquesTalk2Da
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vavi_speech_aquestalk2_AquesTalk2Da
 * Method:    playSync
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_vavi_speech_aquestalk2_AquesTalk2Da_playSync
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     vavi_speech_aquestalk2_AquesTalk2Da
 * Method:    setPhont
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_vavi_speech_aquestalk2_AquesTalk2Da_setPhont
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     vavi_speech_aquestalk2_AquesTalk2Da
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_vavi_speech_aquestalk2_AquesTalk2Da_create
  (JNIEnv *, jobject);

/*
 * Class:     vavi_speech_aquestalk2_AquesTalk2Da
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vavi_speech_aquestalk2_AquesTalk2Da_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vavi_speech_aquestalk2_AquesTalk2Da
 * Method:    play
 * Signature: (JLjava/lang/String;IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_vavi_speech_aquestalk2_AquesTalk2Da_play
  (JNIEnv *, jobject, jlong, jstring, jint, jint, jstring, jint);

/*
 * Class:     vavi_speech_aquestalk2_AquesTalk2Da
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vavi_speech_aquestalk2_AquesTalk2Da_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vavi_speech_aquestalk2_AquesTalk2Da
 * Method:    isPlay
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_vavi_speech_aquestalk2_AquesTalk2Da_isPlay
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
