/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vavi_speech_aquestalk_AquesTalk */

#ifndef _Included_vavi_speech_aquestalk_AquesTalk
#define _Included_vavi_speech_aquestalk_AquesTalk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vavi_speech_aquestalk_AquesTalk
 * Method:    synthe
 * Signature: (Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_vavi_speech_aquestalk_AquesTalk_synthe
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
