name: GitHub Packages

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      env:
        DOCOMO_GOO_HIRAGANA_API_KEY : ${{ secrets.DOCOMO_GOO_HIRAGANA_API_KEY }}
        RECRUIT_PROOFREADING_API_KEY : ${{ secrets.RECRUIT_PROOFREADING_API_KEY }}
        YAHOOJAPAN_API_KEY : ${{ secrets.YAHOOJAPAN_API_KEY }}
        GOOGLE_APPLICATION_CREDENTIALS : 'tmp/google.json'
        GOOGLE : ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        mkdir tmp
        echo "$GOOGLE" > tmp/google.json
        mvn -B package --file pom.xml -s $GITHUB_WORKSPACE/settings.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -Dmaven.test.skip=true
      env:
        GITHUB_TOKEN: ${{ github.token }}
