# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      env:
        DOCOMO_GOO_HIRAGANA_API_KEY : ${{ secrets.DOCOMO_GOO_HIRAGANA_API_KEY }}
        RECRUIT_PROOFREADING_API_KEY : ${{ secrets.RECRUIT_PROOFREADING_API_KEY }}
        YAHOOJAPAN_API_KEY : ${{ secrets.YAHOOJAPAN_API_KEY }}
        GOOGLE_APPLICATION_CREDENTIALS : tmp/google.json
        GOOGLE : ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        mkdir tmp
        echo "$GOOGLE" > tmp/google.json
        mvn -B package --file pom.xml
